[project]
name = "fastapi-app"
version = "0.1.0"
description = "A FastAPI application"
readme = "README.md"
authors = [
    { name = "zcy", email = "18256985885@163.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
